title: My Mapping Portfolio
description: Spatial Analysis & Interactive Map Gallery
theme: jekyll-theme-minimal
logo: /assets/img/map-icon.png # Optional: Add a logo later
show_downloads: false

# Navigation Links
nav_links:
  - title: Global Seismic Activity Week 9
    url: https://godwyer.github.io/godwyer/Week_9_Assignment.html
   - title: Airline Expenditures in California - Week 8
    url: https://godwyer.github.io/godwyer/Week8Assignment.html
  - title: About the Research
    url: /about/

