title: Spatial Analysis Portfolio
description: Interactive Mapping & Research Gallery
theme: jekyll-theme-minimal
show_downloads: false

# Site Settings
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
